uploads = []
generated = []

[[outputs]]
id = "bPGj7WbVmct0ytTfH2jVf"
uri = "file://exports/download-links-backup-2026-04-29.csv"
type = "table"
title = "Download links backup (production, 2026-04-29)"
